/**
 * Image processing pipeline for the Generator feature.
 *
 * Buffer-based ports of scripts/image-pipeline.ts:
 *   - cleanBwImageBuffer(input: Buffer): Promise<Buffer>
 *       greyscale → flatten → threshold@100 → erode ~30%
 *   - colorizeImageBuffer(bw: Buffer, palette): Promise<Buffer>
 *       1024×1024 canvas, gap-closing dilation, flood-fill enclosed regions,
 *       center-fill for BODY, unlimited expansion against orig_mask,
 *       border-flood-fill to skip background.
 *
 * Used by /api/assemble-category-pdf to produce colored reference thumbnails
 * for items generated by the /api/generate route. The same algorithm runs in
 * scripts/image-pipeline.ts (file-based) for the legacy CLI tools.
 */
import sharp from "sharp";
import type { Palette, RGB } from "./coloring-data";

// ─────────────────────────────────────────────────────────────────────────
// Step 1: clean B&W  (greyscale → flatten → threshold @100 → erode ~30%)
// ─────────────────────────────────────────────────────────────────────────

/**
 * Convert a raw AI B&W image buffer to a clean B&W line-art PNG buffer.
 *  - greyscale
 *  - flatten white bg
 *  - threshold: pixel < 100 → black (0), else white (255)
 *  - erode black lines ~30% (thin them) using a 3×3 morphology
 */
export async function cleanBwImageBuffer(
  input: Buffer,
  options: { threshold?: number; erodePercent?: number } = {}
): Promise<Buffer> {
  const threshold = options.threshold ?? 100;
  const erodePercent = options.erodePercent ?? 30;

  const { data, info } = await sharp(input)
    .greyscale()
    .flatten({ background: { r: 255, g: 255, b: 255 } })
    .resize(1024, 1024, { fit: "cover" })
    .raw()
    .toBuffer({ resolveWithObject: true });

  const w = info.width;
  const h = info.height;
  const channels = info.channels;

  // Threshold → pure black/white single-channel buffer
  const bw = Buffer.alloc(w * h);
  for (let i = 0; i < w * h; i++) {
    const v = data[i * channels]; // greyscale, all channels equal
    bw[i] = v < threshold ? 0 : 255;
  }

  // Erode black lines: pixels with few black neighbors turn white.
  const eroded = Buffer.from(bw);
  for (let y = 1; y < h - 1; y++) {
    for (let x = 1; x < w - 1; x++) {
      const idx = y * w + x;
      if (bw[idx] === 0) {
        let blackN = 0;
        for (let dy = -1; dy <= 1; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            if (dy === 0 && dx === 0) continue;
            if (bw[(y + dy) * w + (x + dx)] === 0) blackN++;
          }
        }
        const surviveThreshold = Math.ceil((8 * erodePercent) / 100);
        if (blackN < surviveThreshold) {
          eroded[idx] = 255; // erode → white
        }
      }
    }
  }

  // Write back as RGB PNG
  const outRgb = Buffer.alloc(w * h * 3);
  for (let i = 0; i < w * h; i++) {
    const v = eroded[i];
    outRgb[i * 3] = v;
    outRgb[i * 3 + 1] = v;
    outRgb[i * 3 + 2] = v;
  }

  return sharp(outRgb, { raw: { width: w, height: h, channels: 3 } })
    .png()
    .toBuffer();
}

// ─────────────────────────────────────────────────────────────────────────
// Step 2: auto-colorize (flood fill enclosed white regions)
// ─────────────────────────────────────────────────────────────────────────

interface Region {
  pixels: number[];
  size: number;
}

/**
 * Colorize a clean B&W image buffer using flood-fill region detection.
 *
 * Algorithm (mirrors scripts/image-pipeline.ts → colorizeImage):
 *   1. Resize to 1000×1000 then place on a 1024×1024 WHITE canvas.
 *   2. Build orig_mask (1 = black line) and fill_mask (gap-closed dilation).
 *   3. Flood-fill 8-connected regions using fill_mask as the boundary.
 *      Keep enclosed regions (non-border-touching) of size >= minSize and
 *      < maxSize.
 *   4. Center-fill from the image center → body region.
 *   5. Combine regions: body first, then sub-regions sorted LARGEST FIRST.
 *   6. EXPAND each region outward against orig_mask (unlimited passes) so
 *      color reaches right up to the real outline.
 *   7. Flood-fill from border to mark background — any uncolored white
 *      pixel NOT connected to the border gets the body color.
 *   8. Apply palette: region[i] → palette[i % palette.length].
 */
export async function colorizeImageBuffer(
  bwBuffer: Buffer,
  palette: Palette,
  options: { whiteThreshold?: number; minSize?: number; maxSize?: number; closeGaps?: number } = {}
): Promise<Buffer> {
  const whiteThreshold = options.whiteThreshold ?? 200;
  const minSize = options.minSize ?? 1;
  const maxSize = options.maxSize ?? 1000000;
  const closeGaps = options.closeGaps ?? 4;

  // Resize to 1000×1000 then extend onto a 1024×1024 WHITE canvas (12px border).
  const resized = await sharp(bwBuffer)
    .resize(1000, 1000, { fit: "cover" })
    .flatten({ background: { r: 255, g: 255, b: 255 } })
    .raw()
    .toBuffer();
  const { data: canvasData, info: canvasInfo } = await sharp(resized, {
    raw: { width: 1000, height: 1000, channels: 3 },
  })
    .extend({
      top: 12,
      bottom: 12,
      left: 12,
      right: 12,
      background: { r: 255, g: 255, b: 255 },
    })
    .raw()
    .toBuffer({ resolveWithObject: true });

  const data = canvasData;
  const w = canvasInfo.width;
  const h = canvasInfo.height;
  const ch = canvasInfo.channels;
  const total = w * h;

  // Luminance
  const lum = new Uint8Array(total);
  for (let i = 0; i < total; i++) {
    if (ch >= 3) {
      lum[i] = (data[i * ch] + data[i * ch + 1] + data[i * ch + 2]) / 3;
    } else {
      lum[i] = data[i * ch];
    }
  }

  // orig_mask: 1 = black line (real outline), 0 = white
  const origMask = new Uint8Array(total);
  for (let i = 0; i < total; i++) {
    origMask[i] = lum[i] <= whiteThreshold ? 1 : 0;
  }

  // fill_mask: gap-closed (dilated black lines)
  const fillMask = new Uint8Array(origMask);
  for (let pass = 0; pass < closeGaps; pass++) {
    const dilated = new Uint8Array(fillMask);
    for (let y = 1; y < h - 1; y++) {
      for (let x = 1; x < w - 1; x++) {
        const idx = y * w + x;
        if (fillMask[idx]) continue;
        if (
          fillMask[(y - 1) * w + x - 1] || fillMask[(y - 1) * w + x] || fillMask[(y - 1) * w + x + 1] ||
          fillMask[y * w + x - 1] || fillMask[y * w + x + 1] ||
          fillMask[(y + 1) * w + x - 1] || fillMask[(y + 1) * w + x] || fillMask[(y + 1) * w + x + 1]
        ) {
          dilated[idx] = 1;
        }
      }
    }
    for (let i = 0; i < total; i++) fillMask[i] = dilated[i];
  }

  // Find enclosed sub-regions via flood-fill against the gap-closed mask.
  const subRegions: Region[] = [];
  const visited = new Uint8Array(total);
  const stack: number[] = new Array(total);

  for (let start = 0; start < total; start++) {
    if (visited[start] || fillMask[start] === 1) continue;

    let head = 0;
    let tail = 0;
    stack[tail++] = start;
    visited[start] = 1;

    const pixelIndices: number[] = [];
    let touchesBorder = false;
    const startY = Math.floor(start / w);
    const startX = start % w;
    if (startX === 0 || startX === w - 1 || startY === 0 || startY === h - 1) {
      touchesBorder = true;
    }

    while (head < tail) {
      const idx = stack[head++];
      pixelIndices.push(idx);
      const y = Math.floor(idx / w);
      const x = idx % w;

      for (let dy = -1; dy <= 1; dy++) {
        const ny = y + dy;
        if (ny < 0 || ny >= h) continue;
        for (let dx = -1; dx <= 1; dx++) {
          if (dx === 0 && dy === 0) continue;
          const nx = x + dx;
          if (nx < 0 || nx >= w) continue;
          const nidx = ny * w + nx;
          if (visited[nidx]) continue;
          if (fillMask[nidx] === 1) continue;
          visited[nidx] = 1;
          if (nx === 0 || nx === w - 1 || ny === 0 || ny === h - 1) {
            touchesBorder = true;
          }
          stack[tail++] = nidx;
        }
      }
    }

    if (!touchesBorder && pixelIndices.length >= minSize && pixelIndices.length < maxSize) {
      subRegions.push({ pixels: pixelIndices, size: pixelIndices.length });
    }
  }

  // Center-fill: find the BODY region.
  let bboxMinX = w, bboxMinY = h, bboxMaxX = 0, bboxMaxY = 0;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (fillMask[y * w + x] === 1) {
        if (x < bboxMinX) bboxMinX = x;
        if (x > bboxMaxX) bboxMaxX = x;
        if (y < bboxMinY) bboxMinY = y;
        if (y > bboxMaxY) bboxMaxY = y;
      }
    }
  }
  const cx = Math.floor((bboxMinX + bboxMaxX) / 2);
  const cy = Math.floor((bboxMinY + bboxMaxY) / 2);

  const bodyRegion: Region | null = (() => {
    let startIdx = cy * w + cx;
    if (fillMask[startIdx] === 1) {
      let found = -1;
      for (let r = 1; r < 50 && found === -1; r++) {
        for (let dy = -r; dy <= r && found === -1; dy++) {
          for (let dx = -r; dx <= r && found === -1; dx++) {
            const nx = cx + dx;
            const ny = cy + dy;
            if (nx < 0 || nx >= w || ny < 0 || ny >= h) continue;
            if (fillMask[ny * w + nx] === 0) {
              found = ny * w + nx;
            }
          }
        }
      }
      if (found === -1) return null;
      startIdx = found;
    }

    const centerVisited = new Uint8Array(total);
    const centerStack: number[] = new Array(total);
    let head = 0;
    let tail = 0;
    centerStack[tail++] = startIdx;
    centerVisited[startIdx] = 1;
    const centerPixels: number[] = [];

    while (head < tail) {
      const idx = centerStack[head++];
      centerPixels.push(idx);
      const y = Math.floor(idx / w);
      const x = idx % w;
      for (let dy = -1; dy <= 1; dy++) {
        const ny = y + dy;
        if (ny < 0 || ny >= h) continue;
        for (let dx = -1; dx <= 1; dx++) {
          if (dx === 0 && dy === 0) continue;
          const nx = x + dx;
          if (nx < 0 || nx >= w) continue;
          const nidx = ny * w + nx;
          if (centerVisited[nidx]) continue;
          if (fillMask[nidx] === 1) continue;
          centerVisited[nidx] = 1;
          centerStack[tail++] = nidx;
        }
      }
    }

    if (centerPixels.length > 100) {
      return { pixels: centerPixels, size: centerPixels.length };
    }
    return null;
  })();

  // Combine regions: body first, then sub-regions largest-first.
  const regions: Region[] = [];
  if (bodyRegion) {
    regions.push(bodyRegion);
  }
  subRegions.sort((a, b) => b.size - a.size);
  regions.push(...subRegions);

  // Build a color map: each pixel → region index (255 = uncolored).
  const colorMap = new Uint8Array(total);
  colorMap.fill(255);
  regions.forEach((region, i) => {
    for (const idx of region.pixels) {
      colorMap[idx] = i;
    }
  });

  // EXPAND each region outward against orig_mask until no more changes.
  let expanding = true;
  let safetyCounter = 0;
  while (expanding && safetyCounter < 30) {
    const next = new Uint8Array(colorMap);
    expanding = false;
    for (let y = 1; y < h - 1; y++) {
      for (let x = 1; x < w - 1; x++) {
        const idx = y * w + x;
        if (origMask[idx] === 1 || colorMap[idx] !== 255) continue;
        let bestRegion = 255;
        for (let dy = -1; dy <= 1 && bestRegion === 255; dy++) {
          const ny = y + dy;
          for (let dx = -1; dx <= 1 && bestRegion === 255; dx++) {
            if (dx === 0 && dy === 0) continue;
            const nidx = ny * w + (x + dx);
            if (colorMap[nidx] !== 255) {
              bestRegion = colorMap[nidx];
            }
          }
        }
        if (bestRegion !== 255) {
          next[idx] = bestRegion;
          expanding = true;
        }
      }
    }
    for (let i = 0; i < total; i++) {
      colorMap[i] = next[i];
    }
    safetyCounter++;
  }

  // Fill remaining whites inside the subject (body color).
  if (bodyRegion) {
    const bgVisited = new Uint8Array(total);
    const bgStack: number[] = new Array(total);
    let bgHead = 0;
    let bgTail = 0;

    for (let x = 0; x < w; x++) {
      for (const y of [0, h - 1]) {
        const idx = y * w + x;
        if (origMask[idx] === 0 && colorMap[idx] === 255 && !bgVisited[idx]) {
          bgVisited[idx] = 1;
          bgStack[bgTail++] = idx;
        }
      }
    }
    for (let y = 0; y < h; y++) {
      for (const x of [0, w - 1]) {
        const idx = y * w + x;
        if (origMask[idx] === 0 && colorMap[idx] === 255 && !bgVisited[idx]) {
          bgVisited[idx] = 1;
          bgStack[bgTail++] = idx;
        }
      }
    }

    while (bgHead < bgTail) {
      const idx = bgStack[bgHead++];
      const y = Math.floor(idx / w);
      const x = idx % w;
      for (let dy = -1; dy <= 1; dy++) {
        const ny = y + dy;
        if (ny < 0 || ny >= h) continue;
        for (let dx = -1; dx <= 1; dx++) {
          if (dx === 0 && dy === 0) continue;
          const nx = x + dx;
          if (nx < 0 || nx >= w) continue;
          const nidx = ny * w + nx;
          if (bgVisited[nidx]) continue;
          if (origMask[nidx] === 0 && colorMap[nidx] === 255) {
            bgVisited[nidx] = 1;
            bgStack[bgTail++] = nidx;
          }
        }
      }
    }

    for (let i = 0; i < total; i++) {
      if (colorMap[i] === 255 && origMask[i] === 0 && !bgVisited[i]) {
        colorMap[i] = 0;
      }
    }
  }

  // Build final output RGB buffer.
  const outRgb = Buffer.alloc(total * 3);
  for (let i = 0; i < total; i++) {
    const v = lum[i];
    outRgb[i * 3] = v;
    outRgb[i * 3 + 1] = v;
    outRgb[i * 3 + 2] = v;
  }
  for (let i = 0; i < total; i++) {
    const regionIdx = colorMap[i];
    if (regionIdx !== 255) {
      const color: RGB = palette[regionIdx % palette.length];
      outRgb[i * 3] = color[0];
      outRgb[i * 3 + 1] = color[1];
      outRgb[i * 3 + 2] = color[2];
    }
  }

  return sharp(outRgb, { raw: { width: w, height: h, channels: 3 } })
    .png()
    .toBuffer();
}

// ─────────────────────────────────────────────────────────────────────────
// Convenience: clean + colorize one buffer, return both buffers
// ─────────────────────────────────────────────────────────────────────────

export interface ProcessedImages {
  bw: Buffer;      // cleaned B&W
  color: Buffer;  // auto-colorized
}

export async function processItemBuffer(
  rawBw: Buffer,
  palette: Palette
): Promise<ProcessedImages> {
  const bw = await cleanBwImageBuffer(rawBw);
  const color = await colorizeImageBuffer(bw, palette);
  return { bw, color };
}
