import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb as pdfRgb } from "pdf-lib";
import { getCategory, listItems, getThemePalette } from "@/lib/category-store";
import { getPalette, type Palette } from "@/lib/coloring-data";
import {
  PAGE_WIDTH,
  PAGE_HEIGHT,
  REF_SIZE,
  REF_X,
  REF_Y,
  BW_SIZE,
  BW_X,
  BW_Y,
  TITLE_Y,
  PAGE_NUM_X,
  PAGE_NUM_Y,
} from "@/lib/coloring-data";
import { coloringPageExists, readFile } from "@/lib/blob-storage";
import { cleanBwImageBuffer, colorizeImageBuffer } from "@/lib/image-pipeline";
import sharp from "sharp";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60; // Vercel Pro limit — assembling 100 pages of images can take a while

// ─────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────

interface AssembleBody {
  categorySlug?: string;
  itemNames?: string[];
  pageOrder?: number[]; // optional ordering — defaults to itemNames order
}

interface ItemPage {
  itemName: string;
  rawBw: Buffer | null;   // original generated B&W PNG bytes (or null if missing)
  colorPng: Buffer | null; // 86×86 colored reference thumbnail (or null)
}

/**
 * POST /api/assemble-category-pdf
 *
 * Assembles a coloring-book PDF for a category, using the B&W images already
 * generated by /api/generate (stored in Vercel Blob / public/downloads/).
 *
 * Layout (matches the legacy build_pdf.py + scripts/image-pipeline.ts):
 *   - Page size: 612×792 pt (8.5×11 in)
 *   - Colored reference: 86×86 at top-left (KDP 0.4" margin)
 *   - B&W coloring image: 380×380 centered horizontally, y=132
 *   - Item title: 24pt Helvetica-Bold centered at y=527
 *   - Page number: 10pt Helvetica at (546, 740)
 *
 * Body:
 *   categorySlug  string    — e.g. "Dinosaurs"
 *   itemNames     string[]  — items to include, in order
 *   pageOrder     number[]? — optional reordering (defaults to itemNames order)
 *
 * Returns:
 *   { success, pdf: dataUri, pages, requestedItems, missingItems }
 */
export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as AssembleBody;
    const categorySlug = (body.categorySlug ?? "").trim();
    const itemNames = Array.isArray(body.itemNames) ? body.itemNames : [];

    if (!categorySlug) {
      return NextResponse.json(
        { success: false, error: "categorySlug is required" },
        { status: 400 }
      );
    }
    if (itemNames.length === 0) {
      return NextResponse.json(
        { success: false, error: "itemNames must be a non-empty array" },
        { status: 400 }
      );
    }

    // Optional page reordering
    const order = Array.isArray(body.pageOrder) && body.pageOrder.length === itemNames.length
      ? body.pageOrder
      : itemNames.map((_, i) => i);

    const category = await getCategory(categorySlug);
    if (!category) {
      return NextResponse.json(
        { success: false, error: `Category "${categorySlug}" not found` },
        { status: 404 }
      );
    }

    // Resolve item palettes (per-item if defined, else category-themed)
    const allItems = await listItems(category.id, false);
    const itemsByName = new Map(allItems.map((it) => [it.name, it]));

    // ── Build pages: fetch raw B&W, clean, colorize for the reference thumbnail ─
    const pages: ItemPage[] = [];
    let missingCount = 0;

    for (const itemName of itemNames) {
      const exists = await coloringPageExists(categorySlug, itemName);
      if (!exists.exists || exists.sizeBytes < 5 * 1024 || !exists.url) {
        // Image not generated yet — skip with a warning.
        missingCount++;
        pages.push({ itemName, rawBw: null, colorPng: null });
        continue;
      }

      try {
        const rawBw = await readFile(exists.url);

        // Pick palette with this priority:
        // 1. Per-item palette (if explicitly set in DB — rare)
        // 2. getPalette() from coloring-data.ts — looks up natural palettes
        //    by item name (e.g. Ladybug = red+black, Bee = yellow+black,
        //    Butterfly = orange+blue+yellow). This gives DIVERSE colors
        //    per item instead of all-same-theme-color.
        // 3. Category theme palette (fallback for unknown items)
        const item = itemsByName.get(itemName);
        let palette: Palette;
        if (item?.palette && item.palette.length > 0) {
          // Per-item palette stored in DB (e.g. user customized it)
          palette = item.palette;
        } else {
          // Try natural palette lookup first (gives per-item diversity)
          const naturalPalette = getPalette(itemName, category.name);
          if (naturalPalette && naturalPalette.length > 0) {
            palette = naturalPalette;
          } else {
            // Last resort: category theme palette
            const themePalette = getThemePalette(category.themeColor);
            palette = themePalette.length > 0 ? themePalette : getPalette(itemName, category.name);
          }
        }

        // Build the colored reference thumbnail (86×86) using the full pipeline.
        const cleanedBw = await cleanBwImageBuffer(rawBw);
        const colorFull = await colorizeImageBuffer(cleanedBw, palette);
        const colorThumb = await sharp(colorFull)
          .resize(REF_SIZE, REF_SIZE, { fit: "cover" })
          .png()
          .toBuffer();

        pages.push({ itemName, rawBw, colorPng: colorThumb });
      } catch (err) {
        console.error(`[/api/assemble-category-pdf] item "${itemName}" failed:`, err);
        missingCount++;
        pages.push({ itemName, rawBw: null, colorPng: null });
      }
    }

    // ── Build the PDF ──────────────────────────────────────────────────
    const pdfDoc = await PDFDocument.create();
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

    let pageNum = 0;
    for (const idx of order) {
      if (idx < 0 || idx >= pages.length) continue;
      const page = pages[idx];
      pageNum++;
      const pdfPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

      // Background: white
      pdfPage.drawRectangle({
        x: 0,
        y: 0,
        width: PAGE_WIDTH,
        height: PAGE_HEIGHT,
        color: pdfRgb(1, 1, 1),
      });

      // Colored reference thumbnail (top-left, KDP-compliant 0.4" margin)
      if (page.colorPng) {
        try {
          const colorImg = await pdfDoc.embedPng(page.colorPng);
          pdfPage.drawImage(colorImg, {
            x: REF_X,
            y: PAGE_HEIGHT - REF_Y - REF_SIZE, // top-left origin → flip y
            width: REF_SIZE,
            height: REF_SIZE,
          });
        } catch (err) {
          console.error("[/api/assemble-category-pdf] embed color failed:", err);
        }
      } else {
        // Draw a placeholder rect
        pdfPage.drawRectangle({
          x: REF_X,
          y: PAGE_HEIGHT - REF_Y - REF_SIZE,
          width: REF_SIZE,
          height: REF_SIZE,
          borderColor: pdfRgb(0.8, 0.8, 0.8),
          borderWidth: 1,
          color: pdfRgb(0.95, 0.95, 0.95),
        });
      }

      // B&W coloring image (centered, y=132 from bottom)
      if (page.rawBw) {
        try {
          // Re-clean the B&W image at full size for the printable page.
          const bwPng = await cleanBwImageBuffer(page.rawBw);
          const bwImg = await pdfDoc.embedPng(bwPng);
          pdfPage.drawImage(bwImg, {
            x: BW_X,
            y: PAGE_HEIGHT - BW_Y - BW_SIZE,
            width: BW_SIZE,
            height: BW_SIZE,
          });
        } catch (err) {
          console.error("[/api/assemble-category-pdf] embed B&W failed:", err);
        }
      } else {
        // Draw a dashed-border placeholder showing the item name
        pdfPage.drawRectangle({
          x: BW_X,
          y: PAGE_HEIGHT - BW_Y - BW_SIZE,
          width: BW_SIZE,
          height: BW_SIZE,
          borderColor: pdfRgb(0.7, 0.7, 0.7),
          borderWidth: 2,
          color: pdfRgb(0.97, 0.97, 0.97),
        });
        pdfPage.drawText("(not generated)", {
          x: BW_X + BW_SIZE / 2 - 60,
          y: PAGE_HEIGHT - BW_Y - BW_SIZE / 2,
          size: 12,
          font: helvetica,
          color: pdfRgb(0.5, 0.5, 0.5),
        });
      }

      // Item title (24pt Helvetica-Bold, centered at y=527 from bottom)
      const title = page.itemName;
      const titleSize = 24;
      const titleWidth = helveticaBold.widthOfTextAtSize(title, titleSize);
      const titleX = (PAGE_WIDTH - titleWidth) / 2;
      pdfPage.drawText(title, {
        x: titleX,
        y: PAGE_HEIGHT - TITLE_Y,
        size: titleSize,
        font: helveticaBold,
        color: pdfRgb(0.15, 0.15, 0.15),
      });

      // Page number (10pt, right-aligned at 546,740 from bottom)
      const numStr = String(pageNum);
      const numWidth = helvetica.widthOfTextAtSize(numStr, 10);
      pdfPage.drawText(numStr, {
        x: PAGE_NUM_X - numWidth,
        y: PAGE_HEIGHT - PAGE_NUM_Y,
        size: 10,
        font: helvetica,
        color: pdfRgb(0.4, 0.4, 0.4),
      });
    }

    const outBytes = await pdfDoc.save();
    const dataUri = `data:application/pdf;base64,${Buffer.from(outBytes).toString("base64")}`;

    return NextResponse.json({
      success: true,
      pdf: dataUri,
      pages: pageNum,
      requestedItems: itemNames.length,
      missingItems: missingCount,
      category: { slug: category.slug, name: category.name },
      asOf: new Date().toISOString(),
    });
  } catch (err) {
    console.error("[/api/assemble-category-pdf] error:", err);
    return NextResponse.json(
      {
        success: false,
        error: err instanceof Error ? err.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
