import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb as pdfRgb } from "pdf-lib";
import { getCategory, listItems, getThemePalette } from "@/lib/category-store";
import { getPalette, type Palette } from "@/lib/coloring-data";
import {
  PAGE_WIDTH,
  PAGE_HEIGHT,
  REF_SIZE,
  REF_X,
  REF_Y,
  BW_SIZE,
  BW_X,
  BW_Y,
  TITLE_Y,
  PAGE_NUM_X,
  PAGE_NUM_Y,
} from "@/lib/coloring-data";
import { coloringPageExists, externalColoringPageExists, readFile, uploadPdf, isBlobConfigured } from "@/lib/blob-storage";
import { cleanBwImageBuffer, colorizeImageBuffer } from "@/lib/image-pipeline";
import { upsertBook } from "@/lib/turso";
import sharp from "sharp";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60; // Vercel Pro limit — assembling 100 pages of images can take a while

// ─────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────

interface AssembleBody {
  categorySlug?: string;
  itemNames?: string[];
  pageOrder?: number[]; // optional ordering — defaults to itemNames order
}

interface ItemPage {
  itemName: string;
  rawBw: Buffer | null;   // original generated B&W PNG bytes (or null if missing)
  colorPng: Buffer | null; // 86×86 colored reference thumbnail (or null)
}

/**
 * POST /api/assemble-category-pdf
 *
 * Assembles a coloring-book PDF for a category, using the B&W images already
 * generated by /api/generate (stored in Vercel Blob / public/downloads/).
 *
 * Layout (matches the legacy build_pdf.py + scripts/image-pipeline.ts):
 *   - Page size: 612×792 pt (8.5×11 in)
 *   - Colored reference: 86×86 at top-left (KDP 0.4" margin)
 *   - B&W coloring image: 380×380 centered horizontally, y=132
 *   - Item title: 24pt Helvetica-Bold centered at y=527
 *   - Page number: 10pt Helvetica at (546, 740)
 *
 * Body:
 *   categorySlug  string    — e.g. "Dinosaurs"
 *   itemNames     string[]  — items to include, in order
 *   pageOrder     number[]? — optional reordering (defaults to itemNames order)
 *
 * Returns:
 *   { success, pdf: dataUri, pages, requestedItems, missingItems }
 */
export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as AssembleBody;
    const categorySlug = (body.categorySlug ?? "").trim();
    const itemNames = Array.isArray(body.itemNames) ? body.itemNames : [];

    if (!categorySlug) {
      return NextResponse.json(
        { success: false, error: "categorySlug is required" },
        { status: 400 }
      );
    }
    if (itemNames.length === 0) {
      return NextResponse.json(
        { success: false, error: "itemNames must be a non-empty array" },
        { status: 400 }
      );
    }

    // pageOrder is resolved AFTER pages are built (see below) — pages.length
    // may be > itemNames.length if external uploads exist.

    const category = await getCategory(categorySlug);
    if (!category) {
      return NextResponse.json(
        { success: false, error: `Category "${categorySlug}" not found` },
        { status: 404 }
      );
    }

    // Resolve item palettes (per-item if defined, else category-themed)
    const allItems = await listItems(category.id, false);
    const itemsByName = new Map(allItems.map((it) => [it.name, it]));

    // ── Build pages: fetch raw B&W, clean, colorize for the reference thumbnail ─
    // For each item, check BOTH:
    //   1. API-generated B&W (at coloring-books/{slug}/bw/{item}.png)
    //   2. Externally uploaded B&W (at coloring-books/{slug}/external/{item}.png)
    // If BOTH exist, BOTH are included as separate pages (page count increases).
    const pages: ItemPage[] = [];
    let missingCount = 0;

    for (const itemName of itemNames) {
      // Helper: process a single B&W image (from API or external) into a page
      const processImage = async (url: string, label: string) => {
        try {
          const rawBw = await readFile(url);

          // Pick palette with this priority:
          // 1. Per-item palette (if explicitly set in DB — rare)
          // 2. getPalette() from coloring-data.ts — natural per-item colors
          // 3. Category theme palette (fallback)
          const item = itemsByName.get(itemName);
          let palette: Palette;
          if (item?.palette && item.palette.length > 0) {
            palette = item.palette;
          } else {
            const naturalPalette = getPalette(itemName, category.name);
            if (naturalPalette && naturalPalette.length > 0) {
              palette = naturalPalette;
            } else {
              const themePalette = getThemePalette(category.themeColor);
              palette = themePalette.length > 0 ? themePalette : getPalette(itemName, category.name);
            }
          }

          const cleanedBw = await cleanBwImageBuffer(rawBw);
          const colorFull = await colorizeImageBuffer(cleanedBw, palette);
          // Use 2× resolution for the colored reference thumbnail (172×172)
          // with lanczos3 kernel for high-quality downscaling from 2048→172.
          const colorThumb = await sharp(colorFull)
            .resize(REF_SIZE * 2, REF_SIZE * 2, { fit: "cover", kernel: "lanczos3" })
            .png({ quality: 100, compressionLevel: 0 })
            .toBuffer();

          pages.push({ itemName: label, rawBw, colorPng: colorThumb });
        } catch (err) {
          console.error(`[/api/assemble-category-pdf] item "${label}" failed:`, err);
          missingCount++;
          pages.push({ itemName: label, rawBw: null, colorPng: null });
        }
      };

      // 1. Check API-generated image
      const apiExists = await coloringPageExists(categorySlug, itemName);
      if (apiExists.exists && apiExists.sizeBytes >= 5 * 1024 && apiExists.url) {
        await processImage(apiExists.url, itemName);
      }

      // 2. Check externally uploaded image (additional — doesn't replace API)
      const extExists = await externalColoringPageExists(categorySlug, itemName);
      if (extExists.exists && extExists.sizeBytes >= 5 * 1024 && extExists.url) {
        // Label external images with "(2)" suffix so the user can distinguish
        await processImage(extExists.url, `${itemName} (2)`);
      }

      // If neither API nor external exists, mark as missing
      if (!apiExists.exists && !extExists.exists) {
        missingCount++;
        pages.push({ itemName, rawBw: null, colorPng: null });
      }
    }

    // ── Build the PDF ──────────────────────────────────────────────────
    // Resolve page order NOW that we know the actual page count (which may
    // be > itemNames.length if external uploads exist).
    const order = Array.isArray(body.pageOrder) && body.pageOrder.length === pages.length
      ? body.pageOrder
      : pages.map((_, i) => i);

    const pdfDoc = await PDFDocument.create();
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

    let pageNum = 0;
    for (const idx of order) {
      if (idx < 0 || idx >= pages.length) continue;
      const page = pages[idx];
      pageNum++;
      const pdfPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

      // Background: white
      pdfPage.drawRectangle({
        x: 0,
        y: 0,
        width: PAGE_WIDTH,
        height: PAGE_HEIGHT,
        color: pdfRgb(1, 1, 1),
      });

      // Colored reference thumbnail (top-left, KDP-compliant 0.4" margin)
      if (page.colorPng) {
        try {
          const colorImg = await pdfDoc.embedPng(page.colorPng);
          pdfPage.drawImage(colorImg, {
            x: REF_X,
            y: PAGE_HEIGHT - REF_Y - REF_SIZE, // top-left origin → flip y
            width: REF_SIZE,
            height: REF_SIZE,
          });
        } catch (err) {
          console.error("[/api/assemble-category-pdf] embed color failed:", err);
        }
      } else {
        // Draw a placeholder rect
        pdfPage.drawRectangle({
          x: REF_X,
          y: PAGE_HEIGHT - REF_Y - REF_SIZE,
          width: REF_SIZE,
          height: REF_SIZE,
          borderColor: pdfRgb(0.8, 0.8, 0.8),
          borderWidth: 1,
          color: pdfRgb(0.95, 0.95, 0.95),
        });
      }

      // B&W coloring image (centered, y=132 from bottom)
      if (page.rawBw) {
        try {
          // Re-clean the B&W image at full resolution (2048×2048) for the printable page.
          // No compression — preserves line art crispness for print.
          const bwPng = await cleanBwImageBuffer(page.rawBw);
          const bwImg = await pdfDoc.embedPng(bwPng);
          pdfPage.drawImage(bwImg, {
            x: BW_X,
            y: PAGE_HEIGHT - BW_Y - BW_SIZE,
            width: BW_SIZE,
            height: BW_SIZE,
          });
        } catch (err) {
          console.error("[/api/assemble-category-pdf] embed B&W failed:", err);
        }
      } else {
        // Draw a dashed-border placeholder showing the item name
        pdfPage.drawRectangle({
          x: BW_X,
          y: PAGE_HEIGHT - BW_Y - BW_SIZE,
          width: BW_SIZE,
          height: BW_SIZE,
          borderColor: pdfRgb(0.7, 0.7, 0.7),
          borderWidth: 2,
          color: pdfRgb(0.97, 0.97, 0.97),
        });
        pdfPage.drawText("(not generated)", {
          x: BW_X + BW_SIZE / 2 - 60,
          y: PAGE_HEIGHT - BW_Y - BW_SIZE / 2,
          size: 12,
          font: helvetica,
          color: pdfRgb(0.5, 0.5, 0.5),
        });
      }

      // Item title (24pt Helvetica-Bold, centered at y=527 from bottom)
      const title = page.itemName;
      const titleSize = 24;
      const titleWidth = helveticaBold.widthOfTextAtSize(title, titleSize);
      const titleX = (PAGE_WIDTH - titleWidth) / 2;
      pdfPage.drawText(title, {
        x: titleX,
        y: PAGE_HEIGHT - TITLE_Y,
        size: titleSize,
        font: helveticaBold,
        color: pdfRgb(0.15, 0.15, 0.15),
      });

      // Page number (10pt, right-aligned at 546,740 from bottom)
      const numStr = String(pageNum);
      const numWidth = helvetica.widthOfTextAtSize(numStr, 10);
      pdfPage.drawText(numStr, {
        x: PAGE_NUM_X - numWidth,
        y: PAGE_HEIGHT - PAGE_NUM_Y,
        size: 10,
        font: helvetica,
        color: pdfRgb(0.4, 0.4, 0.4),
      });
    }

    // Save PDF with no compression — preserves full image quality.
    // pdf-lib doesn't compress PNGs by default, but we explicitly set
    // useObjectStreams: false to avoid any FlateDecode compression that
    // could degrade image quality.
    const outBytes = await pdfDoc.save({
      useObjectStreams: false,
    });
    const pdfBuffer = Buffer.from(outBytes);

    // ── Save the PDF to Vercel Blob + create a ColoringBook record ────
    // This makes the PDF appear in the "Coloring Book PDF" tab (where the
    // user can download it) and the "Edit PDF" tab (where they can
    // rearrange pages, add blank pages, etc.).
    let pdfUrl: string;
    let sizeBytes: number = pdfBuffer.length;

    if (isBlobConfigured()) {
      // Upload to Vercel Blob — returns a persistent CDN URL
      const upload = await uploadPdf(category.slug, pdfBuffer);
      pdfUrl = upload.url;
    } else {
      // Local dev fallback — return a data URI (no Blob upload)
      pdfUrl = `data:application/pdf;base64,${pdfBuffer.toString("base64")}`;
    }

    // Create/update the ColoringBook record so the PDF appears in other tabs
    const bookName = `${category.name} Coloring Book`;
    const itemLabels = pages
      .filter((p) => p.rawBw)
      .map((p) => p.itemName);

    try {
      await upsertBook({
        slug: category.slug,
        name: bookName,
        category: category.name,
        description: `${pages.filter(p => p.rawBw).length} pages — auto-generated via Generator`,
        pages: pageNum,
        sizeBytes,
        pdfUrl,
        items: itemLabels,
      });
    } catch (bookErr) {
      // Non-fatal — the PDF is still returned to the user even if the
      // ColoringBook record fails (e.g. table doesn't exist yet).
      console.error("[/api/assemble-category-pdf] upsertBook failed:", bookErr);
    }

    return NextResponse.json({
      success: true,
      pdf: pdfUrl,  // Blob URL (production) or data URI (local dev)
      pages: pageNum,
      requestedItems: itemNames.length,
      missingItems: missingCount,
      category: { slug: category.slug, name: category.name },
      bookName,
      syncedToLibrary: isBlobConfigured(), // true = also visible in Coloring Book PDF + Edit PDF tabs
      asOf: new Date().toISOString(),
    });
  } catch (err) {
    console.error("[/api/assemble-category-pdf] error:", err);
    return NextResponse.json(
      {
        success: false,
        error: err instanceof Error ? err.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
