import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, rgb, StandardFonts, type PDFFont } from "pdf-lib";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// KDP Paperback Cover dimensions (in points; 1 inch = 72 points)
// Full cover = Back (8.5") + Spine (pageCount × 0.002252") + Front (8.5")
// Height = 11.25" (11" + 0.125" bleed top + 0.125" bleed bottom)
const PT = 72;
const PAGE_W = 8.5 * PT;        // 612 — one cover panel width
const COVER_H = 11.25 * PT;     // 810 — full cover height with bleed
const SPINE_PER_PAGE = 0.002252 * PT; // ~0.162 pts per page (KDP white paper)

/**
 * POST /api/generate-cover
 * Body: {
 *   title: string,
 *   author: string,
 *   pageCount: number,
 *   bgGradient: [string, string],
 *   spineColor?: string,
 *   subtitle?: string,
 * }
 *
 * Generates a KDP-ready paperback cover PDF using pdf-lib:
 *   [ BACK COVER ] [ SPINE ] [ FRONT COVER ]
 * with bleed, title/author text, and a colored gradient background.
 *
 * Returns: { success, pdf: data-uri, width, height, spineWidth, fileName }
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const title: string = (body?.title ?? "Coloring Book").trim();
    const author: string = (body?.author ?? "Unknown Author").trim();
    const subtitle: string = (body?.subtitle ?? "").trim();
    const pageCount: number = Math.max(24, Math.min(828, body?.pageCount ?? 100));
    const bgGradient: [string, string] = Array.isArray(body?.bgGradient) && body.bgGradient.length === 2
      ? [body.bgGradient[0], body.bgGradient[1]]
      : ["#FF6B9D", "#FBA74D"];
    const spineColor: string = body?.spineColor ?? bgGradient[0];
    const designStyle: string = body?.designStyle ?? "classic";
    const thumbnailUrls: string[] = Array.isArray(body?.thumbnailUrls) ? body.thumbnailUrls : [];

    // Spine width in points
    const spineW = pageCount * SPINE_PER_PAGE;
    // Full cover width = back + spine + front
    const fullW = PAGE_W + spineW + PAGE_W;

    const doc = await PDFDocument.create();
    doc.setTitle(`${title} — Cover`);
    doc.setAuthor(author);
    doc.setSubject("Amazon KDP Paperback Cover");

    const page = doc.addPage([fullW, COVER_H]);
    const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await doc.embedFont(StandardFonts.Helvetica);

    // ── Background gradient (horizontal stripes) ─────────────────────
    const c1 = hexToRgb(bgGradient[0]);
    const c2 = hexToRgb(bgGradient[1]);
    const stripes = 120;
    const stripeH = COVER_H / stripes;
    for (let i = 0; i < stripes; i++) {
      const t = i / (stripes - 1);
      const r = Math.round(c1[0] + (c2[0] - c1[0]) * t) / 255;
      const g = Math.round(c1[1] + (c2[1] - c1[1]) * t) / 255;
      const b = Math.round(c1[2] + (c2[2] - c1[2]) * t) / 255;
      page.drawRectangle({
        x: 0,
        y: COVER_H - (i + 1) * stripeH,
        width: fullW,
        height: stripeH + 1,
        color: rgb(r, g, b),
      });
    }

    // ── Spine band (slightly darker) ─────────────────────────────────
    const spineX = PAGE_W;
    const spineRgb = hexToRgb(spineColor);
    const darkSpine = rgb(
      Math.max(0, spineRgb[0] - 40) / 255,
      Math.max(0, spineRgb[1] - 40) / 255,
      Math.max(0, spineRgb[2] - 40) / 255
    );
    page.drawRectangle({
      x: spineX,
      y: 0,
      width: spineW,
      height: COVER_H,
      color: darkSpine,
    });

    // Spine text (only if spine is wide enough) — pdf-lib doesn't support
    // rotated text easily, so we skip spine text for narrow spines.
    // For wider spines, we draw the title character by character vertically.
    if (spineW > 40) {
      const fontSize = Math.min(14, spineW * 0.35);
      const chars = title.split("");
      const charH = fontSize * 1.2;
      const totalH = chars.length * charH;
      let startY = (COVER_H + totalH) / 2;
      for (const ch of chars) {
        const w = helveticaBold.widthOfTextAtSize(ch, fontSize);
        page.drawText(ch, {
          x: spineX + (spineW - w) / 2,
          y: startY - charH,
          size: fontSize,
          font: helveticaBold,
          color: rgb(1, 1, 1),
        });
        startY -= charH;
      }
    }

    // ── Front cover (right panel) ────────────────────────────────────
    const frontX = PAGE_W + spineW;
    const white = rgb(1, 1, 1);

    // Embed thumbnail images (if provided) for design styles
    // Thumbnails are PNG format (generated by pdf-to-img)
    const embeddedThumbs: { img: Awaited<ReturnType<typeof doc.embedPng>>; w: number; h: number }[] = [];
    if (thumbnailUrls.length > 0) {
      for (const url of thumbnailUrls.slice(0, 6)) {
        try {
          const imgRes = await fetch(url + (url.includes("?") ? "&" : "?") + "t=" + Date.now());
          if (imgRes.ok) {
            const imgBuf = Buffer.from(await imgRes.arrayBuffer());
            // Try PNG first (thumbnails are PNG), fall back to JPG
            let embedded;
            try {
              embedded = await doc.embedPng(imgBuf);
            } catch {
              embedded = await doc.embedJpg(imgBuf);
            }
            embeddedThumbs.push({ img: embedded, w: embedded.width, h: embedded.height });
          }
        } catch {
          // skip failed images
        }
      }
    }

    // ── Design Style: "classic" (original layout) ─────────────────────
    if (designStyle === "classic") {
      // Decorative bars
      page.drawRectangle({ x: frontX + 50, y: COVER_H - COVER_H * 0.28 - 3, width: PAGE_W - 100, height: 3, color: rgb(1, 1, 1), opacity: 0.25 });
      page.drawRectangle({ x: frontX + 50, y: COVER_H - COVER_H * 0.78 - 3, width: PAGE_W - 100, height: 3, color: rgb(1, 1, 1), opacity: 0.25 });

      drawCenteredText(page, helveticaBold, title, 42, frontX + 50, COVER_H - COVER_H * 0.35 - 42, PAGE_W - 100, white);
      if (subtitle) drawCenteredText(page, helvetica, subtitle, 18, frontX + 50, COVER_H - COVER_H * 0.5 - 18, PAGE_W - 100, white);
      drawCenteredText(page, helveticaBold, author, 20, frontX + 50, COVER_H - COVER_H * 0.82 - 20, PAGE_W - 100, white);
    }

    // ── Design Style: "gallery" (thumbnails grid + title) ─────────────
    else if (designStyle === "gallery" && embeddedThumbs.length > 0) {
      // Title at top
      drawCenteredText(page, helveticaBold, title, 36, frontX + 40, COVER_H - 80, PAGE_W - 80, white);
      if (subtitle) drawCenteredText(page, helvetica, subtitle, 14, frontX + 40, COVER_H - 120, PAGE_W - 80, white);

      // Thumbnail grid: 3 columns × 2 rows — no borders, just images
      const cols = 3;
      const rows = Math.ceil(embeddedThumbs.length / cols);
      const gridTop = COVER_H - 150;
      const gridBottom = 120;
      const gridH = gridTop - gridBottom;
      const cellW = (PAGE_W - 100) / cols;
      const cellH = gridH / Math.max(rows, 1);
      const thumbSize = Math.min(cellW - 15, cellH - 15);

      embeddedThumbs.forEach((thumb, i) => {
        const col = i % cols;
        const row = Math.floor(i / cols);
        const cx = frontX + 50 + col * cellW + (cellW - thumbSize) / 2;
        const cy = gridTop - (row + 1) * cellH + (cellH - thumbSize) / 2;
        page.drawImage(thumb.img, {
          x: cx, y: cy,
          width: thumbSize, height: thumbSize,
          opacity: 0.9,
        });
      });

      // Author at bottom
      drawCenteredText(page, helveticaBold, author, 18, frontX + 40, 60, PAGE_W - 80, white);
    }

    // ── Design Style: "zigzag" (zigzag colored thumbnails, varied sizes) ─
    else if (designStyle === "zigzag" && embeddedThumbs.length > 0) {
      // Title at top
      drawCenteredText(page, helveticaBold, title, 36, frontX + 40, COVER_H - 70, PAGE_W - 80, white);
      if (subtitle) drawCenteredText(page, helvetica, subtitle, 14, frontX + 40, COVER_H - 105, PAGE_W - 80, white);

      // Zigzag arrangement: thumbnails alternate left/right with varying sizes
      // Scale pattern: large, medium, small, large, medium, small...
      const scales = [0.30, 0.22, 0.16, 0.25, 0.20, 0.14];
      const startY = COVER_H - 140;
      const endY = 100;
      const totalH = startY - endY;
      const stepY = totalH / embeddedThumbs.length;

      embeddedThumbs.forEach((thumb, i) => {
        const scale = scales[i % scales.length];
        const sz = PAGE_W * scale;
        // Alternate left and right
        const isLeft = i % 2 === 0;
        const margin = 30;
        const cx = isLeft
          ? frontX + margin
          : frontX + PAGE_W - margin - sz;
        const cy = startY - (i + 1) * stepY + (stepY - sz) / 2;

        page.drawImage(thumb.img, {
          x: cx,
          y: cy,
          width: sz,
          height: sz,
          opacity: 0.9,
        });
      });

      // Author at bottom
      drawCenteredText(page, helveticaBold, author, 18, frontX + 40, 50, PAGE_W - 80, white);
    }

    // ── Design Style: "zigzag-mixed" (alternating colored/B&W, varied scale) ─
    else if (designStyle === "zigzag-mixed" && embeddedThumbs.length > 0) {
      // Title at top
      drawCenteredText(page, helveticaBold, title, 36, frontX + 40, COVER_H - 70, PAGE_W - 80, white);
      if (subtitle) drawCenteredText(page, helvetica, subtitle, 14, frontX + 40, COVER_H - 105, PAGE_W - 80, white);

      // Mixed zigzag: alternate between colored (full opacity) and B&W (greyed)
      // Scale pattern: varied sizes — big, small, medium, big, small...
      const scales = [0.32, 0.18, 0.25, 0.15, 0.22, 0.28];
      const startY = COVER_H - 140;
      const endY = 100;
      const totalH = startY - endY;
      const stepY = totalH / embeddedThumbs.length;

      embeddedThumbs.forEach((thumb, i) => {
        const scale = scales[i % scales.length];
        const sz = PAGE_W * scale;
        const isLeft = i % 2 === 0;
        const margin = 25;
        const cx = isLeft
          ? frontX + margin
          : frontX + PAGE_W - margin - sz;
        const cy = startY - (i + 1) * stepY + (stepY - sz) / 2;

        // Alternate: even = colored (full opacity), odd = B&W effect (grey opacity)
        const isColored = i % 2 === 0;
        page.drawImage(thumb.img, {
          x: cx,
          y: cy,
          width: sz,
          height: sz,
          opacity: isColored ? 0.9 : 0.4,
        });
      });

      // Author at bottom
      drawCenteredText(page, helveticaBold, author, 18, frontX + 40, 50, PAGE_W - 80, white);
    }

    // Fallback: classic layout (if no thumbnails for gallery/collage/banner)
    else {
      page.drawRectangle({ x: frontX + 50, y: COVER_H - COVER_H * 0.28 - 3, width: PAGE_W - 100, height: 3, color: rgb(1, 1, 1), opacity: 0.25 });
      page.drawRectangle({ x: frontX + 50, y: COVER_H - COVER_H * 0.78 - 3, width: PAGE_W - 100, height: 3, color: rgb(1, 1, 1), opacity: 0.25 });
      drawCenteredText(page, helveticaBold, title, 42, frontX + 50, COVER_H - COVER_H * 0.35 - 42, PAGE_W - 100, white);
      if (subtitle) drawCenteredText(page, helvetica, subtitle, 18, frontX + 50, COVER_H - COVER_H * 0.5 - 18, PAGE_W - 100, white);
      drawCenteredText(page, helveticaBold, author, 20, frontX + 50, COVER_H - COVER_H * 0.82 - 20, PAGE_W - 100, white);
    }

    // ── Back cover (left panel) ──────────────────────────────────────
    const descText = `A fun coloring book with ${pageCount} pages of delightful illustrations. Perfect for kids and adults alike. Each page features clean line art ready to color.`;
    const descLines = wrapText(descText, PAGE_W - 100, helvetica, 11);
    let descY = COVER_H - COVER_H * 0.65 - 11;
    for (const line of descLines) {
      page.drawText(line, {
        x: 50,
        y: descY,
        size: 11,
        font: helvetica,
        color: rgb(1, 1, 1),
        opacity: 0.85,
      });
      descY -= 14;
    }

    // Barcode placeholder (bottom-right of back cover)
    const barcodeW = 120;
    const barcodeH = 60;
    page.drawRectangle({
      x: PAGE_W - barcodeW - 40,
      y: 40,
      width: barcodeW,
      height: barcodeH,
      color: rgb(1, 1, 1),
    });
    const isbnText = "ISBN";
    const isbnW = helveticaBold.widthOfTextAtSize(isbnText, 9);
    page.drawText(isbnText, {
      x: PAGE_W - barcodeW - 40 + (barcodeW - isbnW) / 2,
      y: 40 + barcodeH / 2 - 4,
      size: 9,
      font: helveticaBold,
      color: rgb(0.2, 0.2, 0.2),
    });

    const outBytes = await doc.save();
    const dataUri = `data:application/pdf;base64,${Buffer.from(outBytes).toString("base64")}`;

    const safeTitle = title.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
    const fileName = `${safeTitle || "coloring-book"}-cover.pdf`;

    return NextResponse.json({
      success: true,
      pdf: dataUri,
      width: fullW,
      height: COVER_H,
      spineWidth: spineW,
      pageCount,
      fileName,
    });
  } catch (err) {
    console.error("[/api/generate-cover] error:", err);
    return NextResponse.json(
      {
        success: false,
        error: err instanceof Error ? err.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

// ── Helpers ──────────────────────────────────────────────────────────

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
}

function drawCenteredText(
  page: ReturnType<PDFDocument["addPage"]>,
  font: PDFFont,
  text: string,
  size: number,
  x: number,
  y: number,
  maxWidth: number,
  color: ReturnType<typeof rgb>
) {
  // Truncate if too wide
  let t = text;
  while (font.widthOfTextAtSize(t, size) > maxWidth && t.length > 1) {
    t = t.slice(0, -1);
  }
  if (t !== text) t = t.slice(0, -1) + "…";
  const w = font.widthOfTextAtSize(t, size);
  page.drawText(t, { x: x + (maxWidth - w) / 2, y, size, font, color });
}

function wrapText(text: string, maxWidth: number, font: PDFFont, size: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const test = line ? line + " " + word : word;
    if (font.widthOfTextAtSize(test, size) > maxWidth) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines;
}
